let generate = document.querySelector("#generator");
let output = document.querySelector("#output");

const quotes = [
    "Love what you do to achieve great work. ❤️",
    "In chaos lies opportunity. 🌪️",
    "Success is courage to continue. 🏆",
    "Believe, and you're halfway there. 🌟",
    "Strive to be of value, not just success. 💼",
    "Future belongs to dream believers. 🌈",
    "Don't watch the clock, keep going. ⏰",
    "Face fear for everything you want. 😱",
    "Keep moving, no matter how slow. 🚶‍♂️",
    "Doubt today limits tomorrow's realization. ❓",
    "It's not about falling, it's about rising. 🌅",
    "Quit talking, start doing. 💪",
    "Life is what happens while planning. 📅",
    "You miss every shot you don't take. 🎯",
    "Plant your dreams now. 🌱",
    "Cross the ocean, lose sight of shore. 🌊",
    "Run the day, don't let it run you. 🏃‍♂️",
    "Your thoughts shape your reality. 🧠",
    "Decide who you want to be. 🤔",
    "Failures pave path to success. 🛤️",
    "Discover your purpose, find fulfillment. 🔍",
    "Attitude defines life's outcome. 😎",
    "Regret what you didn't do. 😞",
    "Believe in the impossible. 🌌",
    "Decide who you want to be. 🤔",
    "Sacrifice good for great. 🔄",
    "Risk-taking leads to growth. 🌱",
    "Live your own life, not others'. 👤",
    "Help others to rise. 🤝",
    "We become our thoughts. 💭",
    "Vision is greater than sight. 👁️",
    "Be the change you want. 🌎",
    "Great minds discuss ideas. 🧠",
    "Failure is progress. 📉",
    "True wisdom is knowing nothing. 🤫",
    "Success is the best revenge. 🌟",
    "Talent without effort is wasted. 💔",
    "Focus on what you can do. 🔍",
    "Love what you do. ❤️",
    "Mistakes are lessons. 🎓",
    "Your story shapes your success. 📖",
    "Life goes on. 🔄",
    "Create your future. 🚀",
    "Believe, halfway there. 🌟",
    "Create opportunities. 🌐",
    "Enthusiasm fuels success. 🔥",
    "Hard work breeds luck. 🍀",
    "Happiness precedes success. 😊",
    "Success follows hard work. 🏅",
    "Success and failure's paths similar. ↔️",
    "Success finds the busy. ⏳",
    "Give up good for great. 🌟",
    "Doubt limits tomorrow's realization. ❓",
    "Becoming matters more than achieving. 🌱"
];

generate.addEventListener("click", () => {
    let random = Math.floor(Math.random() * 50) + 1;
    output.textContent = quotes[random]
})